export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';


export const UPDATE_COMPANY_SETTINGS = 'UPDATE_COMPANY_SETTINGS';
export const EMPTY_COMPANY_SETTINGS = 'EMPTY_COMPANY_SETTINGS';


export const UPDATE_CURRENT_INVOICE = 'UPDATE_CURRENT_INVOICE';
export const EMPTY_CURRENT_INVOICE = 'UPDATE_CURRENT_INVOICE';

export const SAVE_INVOICE_TO_DRAFT = 'SAVE_INVOICE_TO_DRAFT';
export const DELETE_DRAFT = 'DELETE_DRAFT';
export const EMPTY_DRAFTS = 'EMPTY_DRAFTS';

export const SAVE_INVOICE = 'SAVE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const EMPTY_INVOICES = 'EMPTY_INVOICES';

export const UPDATE_INVOICE_SETTINGS = 'UPDATE_INVOICE_SETTINGS';
export const EMPTY_INVOICE_SETTINGS = 'EMPTY_INVOICE_SETTINGS';
